name: auto_route_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.5
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true